# Generated by Django 6.0.3 on 2026-04-14 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_alter_menucategory_unique_together_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Menu.menu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.diningtable'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.menuitemprice'),
        ),
    ]
