# Generated by Django 6.0.3 on 2026-04-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_alter_menucategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menucategory',
            unique_together={('menu', 'name')},
        ),
    ]
