# Generated by Django 6.0.3 on 2026-04-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
